<?php
/**
 * Copyright © BradSearch. All rights reserved.
 */
declare(strict_types=1);

namespace BradSearch\ProductFeatures\Test\Unit\Model;

use BradSearch\ProductFeatures\Model\UrlRewriteDataLoader;
use Magento\Framework\App\ResourceConnection;
use Magento\Framework\DB\Adapter\AdapterInterface;
use Magento\Framework\DB\Select;
use PHPUnit\Framework\TestCase;

class UrlRewriteDataLoaderTest extends TestCase
{
    private const PRODUCT_ID = 84009;
    private const STORE_ID = 2;

    public function testStandardProductRewriteWinsOverShorterCustomRewrite(): void
    {
        $path = $this->load([
            $this->row('p1', false, null),
            $this->row('blue-chair.html', true, null),
            $this->row('chairs/blue-chair.html', true, '5'),
        ]);

        $this->assertSame('blue-chair.html', $path);
    }

    public function testShortestRewriteIsUsedWhenThereIsNoStandardOne(): void
    {
        $path = $this->load([
            $this->row('chairs/blue-chair.html', true, '5'),
            $this->row('blue-chair-sale.html', false, null),
        ]);

        $this->assertSame('blue-chair-sale.html', $path);
    }

    public function testProductWithoutRewriteReturnsNull(): void
    {
        $this->assertNull($this->load([]));
    }

    /**
     * @param array<int, array<string, mixed>> $rows
     */
    private function load(array $rows): ?string
    {
        $select = $this->createMock(Select::class);
        $select->method('from')->willReturnSelf();
        $select->method('joinLeft')->willReturnSelf();
        $select->method('where')->willReturnSelf();

        $connection = $this->createMock(AdapterInterface::class);
        $connection->method('getTableName')->willReturnArgument(0);
        $connection->method('select')->willReturn($select);
        $connection->method('fetchAll')->willReturn($rows);

        $resource = $this->createStub(ResourceConnection::class);
        $resource->method('getConnection')->willReturn($connection);

        $loader = new UrlRewriteDataLoader($resource);
        $loader->addToQueue(self::PRODUCT_ID, self::STORE_ID);

        return $loader->getRewrite(self::PRODUCT_ID, self::STORE_ID);
    }

    /**
     * @return array<string, mixed>
     */
    private function row(string $requestPath, bool $autogenerated, ?string $categoryId): array
    {
        return [
            'entity_id' => (string)self::PRODUCT_ID,
            'request_path' => $requestPath,
            'is_autogenerated' => $autogenerated ? '1' : '0',
            'category_id' => $categoryId,
        ];
    }
}
