<?php
/**
 * Copyright © BradSearch. All rights reserved.
 */
declare(strict_types=1);

namespace BradSearch\ProductFeatures\Model;

use Magento\Framework\App\ResourceConnection;

/**
 * Batch loader for URL rewrites to avoid N+1 queries
 *
 * Usage pattern (same as StockDataLoader):
 * 1. Resolvers call addToQueue() to register product IDs
 * 2. Resolvers return a deferred value (ValueFactory callback)
 * 3. When callback is invoked, getRewrite() batch-loads all queued IDs
 * 4. Subsequent calls use cached data
 */
class UrlRewriteDataLoader
{
    /**
     * @var ResourceConnection
     */
    private ResourceConnection $resource;

    /**
     * @var array<string, bool> Queued product+store keys waiting to be loaded
     */
    private array $queue = [];

    /**
     * @var array<string, string|null> Loaded URL rewrites indexed by "productId_storeId"
     */
    private array $loaded = [];

    /**
     * @param ResourceConnection $resource
     */
    public function __construct(ResourceConnection $resource)
    {
        $this->resource = $resource;
    }

    /**
     * Add product ID to the batch queue for a given store
     *
     * @param int $productId
     * @param int $storeId
     * @return void
     */
    public function addToQueue(int $productId, int $storeId): void
    {
        $key = $productId . '_' . $storeId;
        if (!isset($this->loaded[$key])) {
            $this->queue[$key] = ['product_id' => $productId, 'store_id' => $storeId];
        }
    }

    /**
     * Get URL rewrite request_path for a product (triggers batch load if needed)
     *
     * @param int $productId
     * @param int $storeId
     * @return string|null The shortest request_path, or null if no rewrite found
     */
    public function getRewrite(int $productId, int $storeId): ?string
    {
        $this->loadPendingQueue();

        $key = $productId . '_' . $storeId;
        return $this->loaded[$key] ?? null;
    }

    /**
     * Load all queued product URL rewrites in one batch query
     *
     * @return void
     */
    private function loadPendingQueue(): void
    {
        if (empty($this->queue)) {
            return;
        }

        // Group by store_id for efficient querying
        $byStore = [];
        foreach ($this->queue as $entry) {
            $byStore[$entry['store_id']][] = $entry['product_id'];
        }

        $connection = $this->resource->getConnection();
        $urlRewriteTable = $connection->getTableName('url_rewrite');
        $categoryRelationTable = $connection->getTableName('catalog_url_rewrite_product_category');

        foreach ($byStore as $storeId => $productIds) {
            $select = $connection->select()
                ->from(
                    ['url_rewrite' => $urlRewriteTable],
                    ['entity_id', 'request_path', 'is_autogenerated']
                )
                ->joinLeft(
                    ['relation' => $categoryRelationTable],
                    'url_rewrite.url_rewrite_id = relation.url_rewrite_id',
                    ['category_id']
                )
                ->where('url_rewrite.entity_type = ?', 'product')
                ->where('url_rewrite.entity_id IN (?)', $productIds)
                ->where('url_rewrite.store_id = ?', $storeId)
                ->where('url_rewrite.redirect_type = ?', 0);

            $results = $connection->fetchAll($select);

            // Prefer the auto-generated rewrite without a category (Magento's own product URL), then the shortest
            $pathsByProduct = [];
            $ranksByProduct = [];
            foreach ($results as $row) {
                $pid = (int)$row['entity_id'];
                $path = $row['request_path'];
                $isStandard = (int)$row['is_autogenerated'] === 1 && $row['category_id'] === null;
                $rank = [$isStandard ? 0 : 1, strlen($path)];
                if (!isset($ranksByProduct[$pid]) || $rank < $ranksByProduct[$pid]) {
                    $ranksByProduct[$pid] = $rank;
                    $pathsByProduct[$pid] = $path;
                }
            }

            // Store results
            foreach ($productIds as $productId) {
                $key = $productId . '_' . $storeId;
                $this->loaded[$key] = $pathsByProduct[$productId] ?? null;
            }
        }

        $this->queue = [];
    }

    /**
     * Clear cache (useful for testing or long-running processes)
     *
     * @return void
     */
    public function clearCache(): void
    {
        $this->queue = [];
        $this->loaded = [];
    }
}
